# all_moderate_zoom_choice + STRONGER BLUR
# GaussianBlur sigma raised, bilinear downscale more aggressive + higher probability.

image_size: 224

train_transforms:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.RandomResizedCrop
      size: ${transforms.image_size}
    - _target_: torchvision.transforms.v2.RandomAffine
      degrees: 15
      translate:
        - 0.1
        - 0.1
      scale:
        - 0.85
        - 1.15
    - _target_: torchvision.transforms.v2.RandomPerspective
      distortion_scale: 0.2
      p: 0.3
    - _target_: torchvision.transforms.v2.ColorJitter
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    # STRONGER: sigma 0.5-3.5 (was 0.1-2.0), kernel 7 (was 5)
    - _target_: torchvision.transforms.v2.GaussianBlur
      kernel_size: 7
      sigma:
        - 0.5
        - 3.5
    - _target_: torchvision.transforms.v2.RandomApply
      p: 0.7
      transforms:
        - _target_: classifier_training.transforms.RandomJPEGCompression
          quality_min: 15
          quality_max: 75
          p: 0.55
        - _target_: classifier_training.transforms.RandomPixelate
          scale_min: 0.2
          scale_max: 0.7
          p: 0.25
        # STRONGER: p=0.4 (was 0.25), scale 0.15-0.55 (was 0.25-0.7)
        - _target_: classifier_training.transforms.RandomBilinearDownscale
          scale_min: 0.15
          scale_max: 0.55
          p: 0.4
        - _target_: classifier_training.transforms.RandomGaussianNoise
          sigma_min: 5.0
          sigma_max: 28.0
          p: 0.45
        - _target_: torchvision.transforms.v2.RandomChoice
          transforms:
            - _target_: classifier_training.transforms.RandomZoomIn
              min_scale: 0.7
              max_scale: 1.0
              p: 1.0
            - _target_: classifier_training.transforms.RandomZoomOut
              min_scale: 1.1
              max_scale: 1.6
              p: 1.0
    - _target_: classifier_training.transforms.ToFloat32Tensor
      scale: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - _target_: torchvision.transforms.v2.RandomErasing
      p: 0.2
      scale:
        - 0.02
        - 0.15

val_transforms:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: 256
    - _target_: torchvision.transforms.v2.CenterCrop
      size: ${transforms.image_size}
    - _target_: classifier_training.transforms.ToFloat32Tensor
      scale: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

test_transforms:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: 256
    - _target_: torchvision.transforms.v2.CenterCrop
      size: ${transforms.image_size}
    - _target_: classifier_training.transforms.ToFloat32Tensor
      scale: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
