# Basketball jersey OCR transforms - ZOOMOUT-ONLY variant.
# No broadcast degradations, only zoom-out to isolate its effect.

image_size: 224

train_transforms:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.RandomResizedCrop
      size: ${transforms.image_size}
    - _target_: torchvision.transforms.v2.RandomAffine
      degrees: 15
      translate:
        - 0.1
        - 0.1
      scale:
        - 0.85
        - 1.15
    - _target_: torchvision.transforms.v2.RandomPerspective
      distortion_scale: 0.2
      p: 0.3
    - _target_: torchvision.transforms.v2.ColorJitter
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    - _target_: torchvision.transforms.v2.GaussianBlur
      kernel_size: 5
      sigma:
        - 0.1
        - 2.0
    - _target_: classifier_training.transforms.RandomZoomOut
      min_scale: 1.1
      max_scale: 1.5
      p: 0.3
    - _target_: classifier_training.transforms.ToFloat32Tensor
      scale: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - _target_: torchvision.transforms.v2.RandomErasing
      p: 0.2
      scale:
        - 0.02
        - 0.15

val_transforms:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: 256
    - _target_: torchvision.transforms.v2.CenterCrop
      size: ${transforms.image_size}
    - _target_: classifier_training.transforms.ToFloat32Tensor
      scale: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

test_transforms:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: 256
    - _target_: torchvision.transforms.v2.CenterCrop
      size: ${transforms.image_size}
    - _target_: classifier_training.transforms.ToFloat32Tensor
      scale: true
    - _target_: torchvision.transforms.v2.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
