# Hydra config for ResNet50ClassificationModel
# ResNet50 is a larger model; slightly lower default LR appropriate for fine-tuning.
_target_: classifier_training.models.resnet.ResNet50ClassificationModel
num_classes: 43
pretrained: true
learning_rate: 5.0e-5
weight_decay: 1.0e-4
warmup_epochs: 5
label_smoothing: 0.1
warmup_start_factor: 1.0e-3
cosine_eta_min_factor: 0.05
