# Callbacks for SmolVLM2 LoRA fine-tuning
# No EMA, ONNX export, confusion matrix, or visualization (not compatible with VLM)
model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: checkpoints
  filename: "epoch={epoch:02d}-val_acc={val/accuracy:.4f}"
  monitor: val/accuracy
  mode: max
  save_top_k: 3
  save_last: true

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: val/accuracy
  mode: max
  patience: 3
  min_delta: 0.001

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: epoch

rich_progress:
  _target_: lightning.pytorch.callbacks.RichProgressBar
