max_epochs: 100
precision: 16-mixed
accelerator: auto
devices: auto
strategy: auto
val_check_interval: 1.0
log_every_n_steps: 10
enable_checkpointing: true
enable_progress_bar: true
enable_model_summary: true
gradient_clip_val: 1.0
gradient_clip_algorithm: norm
accumulate_grad_batches: 1
num_sanity_val_steps: 2
